---
title: "Rapport CYS"
output:
  pdf_document:
    toc: yes
  html_document:
    number_sections: yes
    toc: yes
    toc_float: yes
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, r,echo=F}
library(ggplot2)
library(gridExtra)
library(ggfortify)
library(leaps)
library(MASS)
library(ggplot2)
```

# Etude des données 


```{r}
Q0 = read.csv("Q_0.csv")
summary(Q0)
```

```{r}
Q0[,'X4b']=Q0[,'X4ba']*4+Q0[,'X4bb']*3+Q0[,'X4bc']*2+Q0[,'X4bd']*1
Q0$X4b
Q0[,'X4a']=Q0[,'X4aa']*4+Q0[,'X4ab']*3+Q0[,'X4ac']*2+Q0[,'X4ad']*1
Q0$X4a
Q0[,'X5a']=Q0[,'X5aa']*4+Q0[,'X5ab']*3+Q0[,'X5ac']*2+Q0[,'X5ad']*1
Q0[,'X3c']=Q0[,'X3ca']*0+Q0[,'X3cb']*1+Q0[,'X3cc']*2+Q0[,'X3cd']*3+Q0[,'X3ce']*4
miss=which(Q0$X4a==0|Q0$X4b==0|Q0$X4a==5|Q0$X4b==5|Q0$X5a==0|Q0$X5a==5)
miss
Q0_3=Q0[,c('X3c','X2b')]
Q0_3[,'X3b']=apply(Q0[,c('X3ba','X3bb','X3bc','X3bd','X3be')],1,max)
Q0_3=Q0_3[,c('X3b','X3c')]
Q0_3$X3b=factor(Q0_3$X3b,levels=c(1,0),labels=c("No","Yes"),ordered = TRUE)
Q0_3$X3c=factor(Q0_3$X3c,levels=c(0,1,2,3,4),labels=c("0h","2h","5h","10h","20h"),ordered = TRUE)
summary(Q0_3)

Q0_4=Q0[-miss,c('X4a','X4b','X5a')]
Q0_4$X4a=factor(Q0_4$X4a,levels=c(1,2,3,4),labels=c("bad","sufficient","good","very good"),ordered = TRUE)
Q0_4$X4b=factor(Q0_4$X4b,levels=c(1,2,3,4),labels=c("bad","sufficient","good","very good"),ordered = TRUE)

Q0_4$X5a=factor(Q0_4$X5a,levels=c(1,2,3,4),labels=c("no","maybe no","yes but with difficulty","yes"),ordered = TRUE)
summary(Q0_4)
str(Q0_4)

```



```{r}
colnames(Q0_3)=c('Playing','Playing time')
summary(Q0_3)
```

```{r}
table(Q0_3$`Playing`,Q0_3$`Playing time`)
```

```{r echo=FALSE}
library(rpart)
library(partykit)
tree.q3=rpart(Playing~.,data=Q0_3,cp=0.0001)
xmat3=xpred.rpart(tree.q3)
xerr3=(xmat3!=as.numeric(Q0_3[,"Playing"]))^2
CVerr3=apply(xerr3,2,sum)
CVerr3
```

```{r echo=FALSE}
tree.dis3=rpart(Playing~.,data=Q0_3,
                control=rpart.control(cp=as.numeric(attributes(which.min(CVerr3))$names)))
plot(as.party(tree.dis3), type="simple")
```

```{r}
Q0_3[,"X2b"]=Q0["X2b"]
Q0_2=Q0_3[,c("Playing","X2b")]
Q0_2$X2b=factor(Q0_2$X2b,levels=c(0,1),labels=c("No","Yes"))
colnames(Q0_2)=c('Playing','Tablette')

summary(Q0_2)
```


```{r}
table(Q0_2$Tablette,Q0_2$Playing)
```


```{r}
Q0_4[,'X6a1']=Q0[-miss,'X6a1a']
Q0_4$X6a1=as.factor(Q0_4$X6a1)
summary(Q0_4$X6a1)
colnames(Q0_4)=c('Electronics','English','E_learning_possibility','E_learning_experience')
```











```{r}
set.seed(100) # initialisation du générateur
# Extraction des échantillons
test.ratio=.2   # part de l'échantillon test
npop=nrow(Q0_4) # nombre de lignes dans les données
nvar=ncol(Q0_4) # nombre de colonnes
# taille de l'échantillon test
ntest=ceiling(npop*test.ratio) 
# indices de l'échantillon test
testi=sample(1:npop,ntest)
# indices de l'échantillon d'apprentissage
appri=setdiff(1:npop,testi)
```

```{r}

# construction de l'échantillon d'apprentissage
datappq=Q0_4[appri,]
# construction de l'échantillon test 
datestq=Q0_4[testi,] 
summary(datappq) # vérification
```



```{r}
table(Q0_4$Electronics,Q0_4$English)
```



```{r echo=FALSE}
library(rpart)
library(partykit)
tree.q5=rpart(E_learning_possibility~.,data=datappq,cp=0.0001)
plot(as.party(tree.q5),type='simple')
xmat5=xpred.rpart(tree.q5)
xerr5=(xmat5!=as.numeric(datappq[,"E_learning_possibility"]))^2
CVerr5=apply(xerr5,2,sum)
CVerr5
```


En cas on veut construire un arbre de régression de l'évolution de la note en fonction d'autres variables

```{r echo=FALSE}
tree.dis5=rpart(E_learning_possibility~.,data=datappq,
                control=rpart.control(cp=as.numeric(attributes(which.min(CVerr5))$names)))
plot(as.party(tree.dis5), type="simple")
```

```{r}
# Calcul des prévisions
pred.treeq5=predict(tree.dis5,newdata=datestq,type="class") 
# Erreur quadratique moyenne de prévision en régression
sum((as.numeric(pred.treeq5)!=as.numeric(datestq[,"E_learning_possibility"])))/nrow(datestq)
```

```{r}
table(pred.treeq5,datestq[,"E_learning_possibility"])
```




```{r}
tree.q4=rpart(English~.,data=datappq,cp=0.001)
plot(as.party(tree.q4),type='simple')
xmat4=xpred.rpart(tree.q4)
xerr4=(xmat4!=as.numeric(datappq[,"English"]))^2
CVerr4=apply(xerr4,2,sum)
CVerr4
```




```{r echo=FALSE}
tree.dis4=rpart(English~.,data=datappq,
                control=rpart.control(cp=as.numeric(attributes(which.min(CVerr4))$names)))
plot(as.party(tree.dis4), type="simple")
```



```{r}
# Calcul des prévisions
pred.treeq4=predict(tree.dis4,newdata=datestq,type="class") 
# Erreur quadratique moyenne de prévision en régression
sum((as.numeric(pred.treeq4)!=as.numeric(datestq[,"English"])))/nrow(datestq)
```




```{r}
table(pred.treeq4,datestq[,"English"])
```



















