---
title: "Q_2"
author: "Viet Minh Thong Le- Dinh Triem Phan"
date: "07/05/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, r,echo=F}
library(ggplot2)
library(gridExtra)
library(ggfortify)
library(leaps)
library(MASS)
library(ggplot2)
```

# Etude des données 


```{r}
Q2 = read.csv("Q_2.csv")
```


```{r}
Q2_1 = Q2[,c("A2a","A2b","A2c","A2d","A2e","A2f")]
summary(Q2_1)
gameper=apply(Q2_1[,c(1:6)],2,mean)
gameper[6]=mean(Q2_1$A2f,na.rm=TRUE)
print(gameper)
```



```{r}
Q2_7=Q2[,c("A1a","A1b","A1c","A1d","A2a","A2b","A2c","A2d","A2e","A2f","A7a")]
Q2_7[is.na(Q2_7)]=0
Q2_7[,'A1']=Q2_7[,'A1a']*0+Q2_7[,'A1b']*1+Q2_7[,'A1c']*2+Q2_7[,'A1d']*3
Q2_7$A2a=factor(Q2_7$A2a,levels=c(0,1),labels=c("No","Yes"))
Q2_7$A2b=factor(Q2_7$A2b,levels=c(0,1),labels=c("No","Yes"))
Q2_7$A2c=factor(Q2_7$A2c,levels=c(0,1),labels=c("No","Yes"))
Q2_7$A2d=factor(Q2_7$A2d,levels=c(0,1),labels=c("No","Yes"))
Q2_7$A2e=factor(Q2_7$A2e,levels=c(0,1),labels=c("No","Yes"))
Q2_7$A2f=factor(Q2_7$A2f,levels=c(0,1),labels=c("No","Yes"))
Q2_7$A7=factor(Q2_7$A7,levels=c(0,1),labels=c("No","Yes"))
Q2_7$A1=factor(Q2_7$A1,levels=c(0,1,2,3),labels=c("once","less_5","5to10","more_10"))

Q2_7=Q2_7[,c(5:10,12,13)]
colnames(Q2_7)=c("Pendu","Audiowords","Check_your_motus","QCM","Check_your_taboo","Flashcards","frequency","Achieved")
summary(Q2_7)
```


```{r}
set.seed(33) # initialisation du générateur
# Extraction des échantillons
test.ratio=.2   # part de l'échantillon test
npop=nrow(Q2_7) # nombre de lignes dans les données
nvar=ncol(Q2_7) # nombre de colonnes
# taille de l'échantillon test
ntest=ceiling(npop*test.ratio) 
# indices de l'échantillon test
testi=sample(1:npop,ntest)
# indices de l'échantillon d'apprentissage
appri=setdiff(1:npop,testi)
```

```{r}

# construction de l'échantillon d'apprentissage
datappq=Q2_7[appri,]
# construction de l'échantillon test 
datestq=Q2_7[testi,] 
summary(datappq) # vérification
```




```{r echo=FALSE}
library(rpart)
library(partykit)
tree.q7=rpart(Achieved~.,data=datappq,cp=0.0001)
xmat7=xpred.rpart(tree.q7)
xerr7=(xmat7!=as.numeric(datappq[,"Achieved"]))^2
CVerr7=apply(xerr7,2,sum)
CVerr7
```




```{r echo=FALSE}
tree.dis7=rpart(Achieved~.,data=datappq,
                control=rpart.control(cp=as.numeric(attributes(which.min(CVerr7))$names)))
plot(as.party(tree.dis7), type="simple")
```


```{r}
Q2_7t=Q2_7
Q2_7t[,"X1B"]=Q2[,"X1B"]

Q2_7t=Q2_7t[-which(is.na(Q2_7t$X1B)),]
colnames(Q2_7t)=c("Pendu","Audiowords","Check_your_motus","QCM","Check_your_taboo","Flashcards","frequency","achieved","Time_CYS")
summary(Q2_7t)
```










```{r}
set.seed(340) # initialisation du générateur
# Extraction des échantillons
test.ratio=.2   # part de l'échantillon test
npop=nrow(Q2_7t) # nombre de lignes dans les données
nvar=ncol(Q2_7t) # nombre de colonnes
# taille de l'échantillon test
ntest=ceiling(npop*test.ratio) 
# indices de l'échantillon test
testi=sample(1:npop,ntest)
# indices de l'échantillon d'apprentissage
appri=setdiff(1:npop,testi)
```

```{r}

# construction de l'échantillon d'apprentissage
datappq=Q2_7t[appri,]
# construction de l'échantillon test 
datestq=Q2_7t[testi,] 
summary(datappq) # vérification
```





```{r}
mean(Q2_7t$Time_CYS)
hist(Q2_7t$Time_CYS,xlab="Time spent on CYS(hours)",ylab="Number of students",main="Histogram")
```



```{r}
tree.q7t=rpart(achieved~.,data=datappq,cp=0.0001)
xmat7t=xpred.rpart(tree.q7t)
xerr7t=(xmat7t!=as.numeric(datappq[,"achieved"]))^2
CVerr7t=apply(xerr7t,2,sum)
CVerr7t
```



```{r echo=FALSE}
tree.dis7t=rpart(achieved~.,data=datappq,
                control=rpart.control(cp=as.numeric(attributes(which.min(CVerr7t))$names)))
plot(as.party(tree.dis7t), type="simple")
```

```{r}
# Calcul des prévisions
pred.treeq7t=predict(tree.dis7t,newdata=datestq,type="class") 
# Erreur quadratique moyenne de prévision en régression
sum((as.numeric(pred.treeq7t)!=as.numeric(datestq[,"achieved"])))/nrow(datestq)
```

```{r}
table(pred.treeq7t,datestq[,"achieved"])
```



